sudo: required

language: cpp

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo docker -v

before_script:
  - sudo docker build . -f Dockerfiles/cpu/Dockerfile -t akiyamalab/megadock:cpu
  
script:
  - sudo docker run  -it akiyamalab/megadock:cpu  megadock -R data/1gcq_r.pdb -L data/1gcq_r.pdb
  
notifications:
  emails:
    - aoyama@bi.c.titech.ac.jp # github@bi.cs.titech.ac.jp
  on_success: always # default: change
  on_failure: always
